<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "pxa_survey"
 *
 * Auto generated by Extension Builder 2017-11-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Survey',
    'description' => 'Create simple survey. Simpel view of result on FE. View results in the BE module',
    'category' => 'plugin',
    'author' => 'Andriy Oprysko',
    'author_email' => '',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.4.2',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.5.99',
            'php' => '7.0.0-7.2.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
